Create ci.yml
cronofy/cronofy-php pull request #109
Opened 2021-06-28 11:09 UTC by Grajo

This is to replace current travis.yml

2021-06-28 12:29 UTC, Grajo commented
Hey I think this is all  we need to **migrate** from **travis** to **circle ci!** However, it still requires not to expect the `continuous-integration/travis-ci` to be executed anymore. I bet this is some setting in the repo that I have currently no access to, due to lack of privileges. I think it will be good practice to add to the `php CI/build` the **Required** tag too, but again this probably needs to be done through repository settings. What do you think @AdamWhittingham ?

2021-06-28 16:42 UTC, AdamWhittingham commented on .github/workflows/ci.yml
> +        php-version: ['7.2']
I think this key is wrong:
```suggestion
        php_version: ['7.2']
```

2021-06-28 16:46 UTC, AdamWhittingham commented
@Grajo Ah, I think you're right and it's a repo level setting to enforce the required checks (if it were a config file in the repo then someone could change it and release without the required check!) - we'll need some help in disabling it.
Otherwise, it looks lie the new builds are failing because the key for PHP version isn't quite right (needs an underscore rather than a `-`)

2021-06-28 16:47 UTC, AdamWhittingham commented on .github/workflows/ci.yml
> +        os: [ubuntu-latest, macos-latest, windows-latest]
Great idea to test more OS's 👍

2021-06-28 16:52 UTC, AdamWhittingham reviewed
Changing `php-version` to `php_version` has fixed the Linux tests but looks like Windows has a path issue we need to work through

2021-06-29 15:26 UTC, Nevett requested changes
Take a look at running tests/linting as part of this also

2021-06-30 13:22 UTC, Nevett approved these changes

2021-06-30 13:23 UTC, merged